/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nanos.nbiz.pos;

import com.nanosl.lib.date.JXDatePicker;
import com.nanosl.nbiz.util.Combo;
import com.nanosl.nbiz.util.Data;
import com.nanosl.nbiz.util.FindMySql;
import static com.nanosl.nbiz.util.Format.yyyy_MM_dd;
import com.nanosl.nbiz.util.NTopComponent;
import com.nanosl.nbiz.util.Printer;
import entity.CollectionReceipt;
import entity.Customer;
import entity.Employee;
import entity.Item;
import entity.PriceList;
import entity.SaleCash;
import entity.SaleInvoice;
import entity.SaleInvoiceHasItem;
import entity.SaleInvoiceHasItemPK;
import entity.Stock;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.Serializable;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.StatusDisplayer;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.nanos.nbiz.pos//POS//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "POSTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "com.nanos.nbiz.pos.POSTopComponent")
@ActionReference(path = "Menu/Sales" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_POSAction",
        preferredID = "POSTopComponent")
@Messages({
    "CTL_POSAction=POS",
    "CTL_POSTopComponent=POS Window",
    "HINT_POSTopComponent=This is a POS window"
})
public final class POSTopComponent extends NTopComponent {

    public POSTopComponent() {
        onLoad();
        setName(Bundle.CTL_POSTopComponent());
        setToolTipText(Bundle.HINT_POSTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datePicker = new JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        invoiceNumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalAmountField = new javax.swing.JTextField();
        totalDiscountField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paidAmountField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        remainingAmountField = new javax.swing.JTextField();
        searchCustomerButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        receiptNumberField = new javax.swing.JTextField();
        printCheckBox = new javax.swing.JCheckBox();
        anotherButton = new javax.swing.JButton();
        lastInvoiceNumberField = new javax.swing.JTextField();
        searchItemButton = new javax.swing.JButton();
        employeeComboBox = new javax.swing.JComboBox();
        historyComboBox = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datePicker.setName("datePicker"); // NOI18N
        datePicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datePickerKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel2.text")); // NOI18N

        invoiceNumberField.setEditable(false);
        invoiceNumberField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        invoiceNumberField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        invoiceNumberField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceNumberFieldMouseClicked(evt);
            }
        });
        invoiceNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceNumberFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel3.text")); // NOI18N

        customerComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        customerComboBox.setName("customerComboBox"); // NOI18N
        customerComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerComboBoxFocusGained(evt);
            }
        });
        customerComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerComboBoxKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel4.text")); // NOI18N

        itemComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        itemComboBox.setName("itemComboBox"); // NOI18N
        itemComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemComboBoxMouseClicked(evt);
            }
        });
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });
        itemComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemComboBoxFocusGained(evt);
            }
        });
        itemComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemComboBoxKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel5.text")); // NOI18N

        quantityField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel6.text")); // NOI18N

        priceField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Code", "Description", "Price", "Quantity", "Net", "Discount", "D%", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title8_1")); // NOI18N
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title1")); // NOI18N
            table.getColumnModel().getColumn(2).setPreferredWidth(300);
            table.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title2")); // NOI18N
            table.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title3")); // NOI18N
            table.getColumnModel().getColumn(3).setCellRenderer(rightAlignCell);
            table.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title4")); // NOI18N
            table.getColumnModel().getColumn(4).setCellRenderer(rightAlignCell);
            table.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title5")); // NOI18N
            table.getColumnModel().getColumn(5).setCellRenderer(rightAlignCell);
            table.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title6")); // NOI18N
            table.getColumnModel().getColumn(6).setCellRenderer(rightAlignCell);
            table.getColumnModel().getColumn(7).setPreferredWidth(50);
            table.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title7")); // NOI18N
            table.getColumnModel().getColumn(7).setCellRenderer(rightAlignCell);
            table.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.table.columnModel.title8")); // NOI18N
            table.getColumnModel().getColumn(8).setCellRenderer(rightAlignCell);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel8.text")); // NOI18N

        processButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(processButton, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.processButton.text")); // NOI18N
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(clearButton, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.clearButton.text")); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        totalAmountField.setEditable(false);
        totalAmountField.setBackground(new java.awt.Color(255, 255, 255));
        totalAmountField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        totalAmountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountFieldActionPerformed(evt);
            }
        });

        totalDiscountField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        totalDiscountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalDiscountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDiscountFieldActionPerformed(evt);
            }
        });
        totalDiscountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalDiscountFieldFocusLost(evt);
            }
        });
        totalDiscountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalDiscountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalDiscountFieldKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel9.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel7.text")); // NOI18N

        discountField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        discountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountFieldActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(quantityLabel, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.quantityLabel.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel10.text")); // NOI18N

        paidAmountField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        paidAmountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        paidAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidAmountFieldActionPerformed(evt);
            }
        });
        paidAmountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paidAmountFieldFocusGained(evt);
            }
        });
        paidAmountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidAmountFieldKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel11.text")); // NOI18N

        remainingAmountField.setEditable(false);
        remainingAmountField.setBackground(new java.awt.Color(255, 255, 255));
        remainingAmountField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        remainingAmountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        searchCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(searchCustomerButton, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.searchCustomerButton.text")); // NOI18N
        searchCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.jLabel12.text")); // NOI18N

        receiptNumberField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        receiptNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptNumberFieldActionPerformed(evt);
            }
        });
        receiptNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                receiptNumberFieldKeyReleased(evt);
            }
        });

        printCheckBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(printCheckBox, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.printCheckBox.text")); // NOI18N

        anotherButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(anotherButton, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.anotherButton.text")); // NOI18N
        anotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherButtonActionPerformed(evt);
            }
        });

        lastInvoiceNumberField.setEditable(false);
        lastInvoiceNumberField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lastInvoiceNumberField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lastInvoiceNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastInvoiceNumberFieldActionPerformed(evt);
            }
        });

        searchItemButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(searchItemButton, org.openide.util.NbBundle.getMessage(POSTopComponent.class, "POSTopComponent.searchItemButton.text")); // NOI18N
        searchItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemButtonActionPerformed(evt);
            }
        });

        employeeComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        employeeComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeComboBoxMouseClicked(evt);
            }
        });
        employeeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeComboBoxActionPerformed(evt);
            }
        });
        employeeComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeComboBoxKeyPressed(evt);
            }
        });

        historyComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        historyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "c", "d" }));
        historyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(processButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lastInvoiceNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anotherButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(historyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(printCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(receiptNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalDiscountField)
                            .addComponent(remainingAmountField)
                            .addComponent(paidAmountField)
                            .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchItemButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(invoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel)
                    .addComponent(searchItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(processButton)
                            .addComponent(clearButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastInvoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalDiscountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(receiptNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(employeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paidAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainingAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void datePickerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datePickerKeyPressed
        if (evt.getKeyCode() == 10) {
            customerComboBox.requestFocus();
        }
    }//GEN-LAST:event_datePickerKeyPressed

    private void invoiceNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceNumberFieldActionPerformed
        if (!invoiceNumberField.getText().trim().equals("")) {
            datePicker.requestFocus();
        }
    }//GEN-LAST:event_invoiceNumberFieldActionPerformed

    private void customerComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerComboBoxKeyPressed
        if (evt.getKeyCode() == 10) {
            itemComboBox.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F2) {
            searchCustomer();
        }
    }//GEN-LAST:event_customerComboBoxKeyPressed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        Item item = (Item) itemComboBox.getSelectedItem();
        if (item == null) {
            return;
        }
        PriceList priceList = item.getPriceList();
        manager.clearCache();
//        Stock stock = manager.find(Stock.class, item.getCode());
        double quantity = FindMySql.quantityByItemCode(item.getCode());
//        double quantity = stock.getQuantity() == null ? 0 : item.getStock().getQuantity();
        quantityLabel.setText(nf2d.format(quantity));
        double price = priceList.getSellingPack() == null ? 0 : priceList.getSellingPack();
        priceField.setText(nf2d.format(price));
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void itemComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemComboBoxKeyPressed
        if (evt.getKeyCode() == 10) {
            quantityField.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F2) {
            searchItem();
        } else if (evt.getKeyCode() == 192 || evt.getKeyCode() == KeyEvent.VK_ADD || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            employeeComboBox.requestFocus();
        }
    }//GEN-LAST:event_itemComboBoxKeyPressed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        priceField.setSelectionStart(0);
        priceField.requestFocus();
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        addToTable();
        itemComboBox.requestFocus();
    }//GEN-LAST:event_priceFieldActionPerformed

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        if (evt.getKeyCode() == 127 && table.getSelectedRow() > -1) {
            tableModel.removeRow(table.getSelectedRow());
            calcTotal();
        }
    }//GEN-LAST:event_tableKeyReleased

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        process();
    }//GEN-LAST:event_processButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void totalDiscountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDiscountFieldActionPerformed
        paidAmountField.requestFocus();
        paidAmountField.selectAll();
    }//GEN-LAST:event_totalDiscountFieldActionPerformed

    private void totalDiscountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalDiscountFieldKeyReleased
        if (totalDiscountField.getText().equals("`") || totalDiscountField.getText().equals("+")) {
            totalDiscountField.setText("0");
            totalDiscountField.selectAll();
        }
        substractDiscount();
    }//GEN-LAST:event_totalDiscountFieldKeyReleased

    private void discountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountFieldActionPerformed
        addToTable();
        itemComboBox.requestFocus();
    }//GEN-LAST:event_discountFieldActionPerformed

    private void paidAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidAmountFieldActionPerformed
        process();
    }//GEN-LAST:event_paidAmountFieldActionPerformed

    private void paidAmountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountFieldKeyReleased
        if (paidAmountField.getText().equals("`") || paidAmountField.getText().equals("+")) {
            paidAmountField.setText("0");
            paidAmountField.selectAll();
        }
        calcRemaining();
    }//GEN-LAST:event_paidAmountFieldKeyReleased

    private void searchCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerButtonActionPerformed
        searchCustomer();
    }//GEN-LAST:event_searchCustomerButtonActionPerformed

    private void receiptNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptNumberFieldActionPerformed
        paidAmountField.requestFocus();
    }//GEN-LAST:event_receiptNumberFieldActionPerformed

    private void receiptNumberFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiptNumberFieldKeyReleased
    }//GEN-LAST:event_receiptNumberFieldKeyReleased

    private void customerComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerComboBoxFocusGained
        StatusDisplayer.getDefault().setStatusText("F2 for Search");
    }//GEN-LAST:event_customerComboBoxFocusGained

    private void itemComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemComboBoxFocusGained
        StatusDisplayer.getDefault().setStatusText("F2 for Search");
    }//GEN-LAST:event_itemComboBoxFocusGained

    private void anotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherButtonActionPerformed
        TopComponent win = new POSTopComponent();
        win.open();
        win.requestActive();
    }//GEN-LAST:event_anotherButtonActionPerformed

    private void lastInvoiceNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastInvoiceNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastInvoiceNumberFieldActionPerformed

    private void totalAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountFieldActionPerformed

    private void totalDiscountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalDiscountFieldKeyPressed
        if (evt.getKeyCode() == 192 || evt.getKeyCode() == KeyEvent.VK_ADD || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            paidAmountField.requestFocus();
            paidAmountField.selectAll();
        }
    }//GEN-LAST:event_totalDiscountFieldKeyPressed

    private void searchItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemButtonActionPerformed
        searchItem();
    }//GEN-LAST:event_searchItemButtonActionPerformed

    private void totalDiscountFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalDiscountFieldFocusLost
        if (totalDiscountField.getText().equalsIgnoreCase("+")) {
            totalDiscountField.setText("0.0");
        }
    }//GEN-LAST:event_totalDiscountFieldFocusLost

    private void paidAmountFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidAmountFieldFocusGained
        if (paidAmountField.getText().equalsIgnoreCase("+")) {
            paidAmountField.setText("");
        }
    }//GEN-LAST:event_paidAmountFieldFocusGained

    private void invoiceNumberFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceNumberFieldMouseClicked
        searchInvoice();
    }//GEN-LAST:event_invoiceNumberFieldMouseClicked

    private void employeeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeComboBoxActionPerformed

    }//GEN-LAST:event_employeeComboBoxActionPerformed
    int enterCount = 0;
    private void employeeComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeComboBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            enterCount++;
            if (enterCount < 2) {
                return;
            }
            for (int i = 0; i < table.getRowCount(); i++) {
                if (Double.parseDouble(table.getValueAt(i, 6).toString()) > 0) {
                    paidAmountField.requestFocus();
                    paidAmountField.selectAll();
                    return;
                }
            }
            totalDiscountField.requestFocus();
            totalDiscountField.selectAll();
            enterCount = 0;
        }
    }//GEN-LAST:event_employeeComboBoxKeyPressed

    private void itemComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemComboBoxMouseClicked
//        showNotification("Refreshed", "Items Refreshed");
//        JPopupMenu jPopupMenu = new JPopupMenu("Refresh");
//        jPopupMenu.add(new JMenuItem("Click Me!"));
//        jPopupMenu.show(itemComboBox, itemComboBox.getX(), itemComboBox.getY());

    }//GEN-LAST:event_itemComboBoxMouseClicked

    private void employeeComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeComboBoxMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            Combo.fillEmployees(employeeComboBox);
            showNotification("Refreshed", "Employee list Refreshed");
//            JPopupMenu jPopupMenu = new JPopupMenu("Refresh");
//            jPopupMenu.add(new JMenuItem("Click Me!"));
//            jPopupMenu.show(employeeComboBox, employeeComboBox.getX(), employeeComboBox.getY());
        }

    }//GEN-LAST:event_employeeComboBoxMouseClicked

    private void historyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyComboBoxActionPerformed
        fillInvoice(historyComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_historyComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anotherButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<Customer> customerComboBox;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JTextField discountField;
    private javax.swing.JComboBox employeeComboBox;
    private javax.swing.JComboBox historyComboBox;
    private javax.swing.JTextField invoiceNumberField;
    private javax.swing.JComboBox<Item> itemComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastInvoiceNumberField;
    private javax.swing.JTextField paidAmountField;
    private javax.swing.JTextField priceField;
    private javax.swing.JCheckBox printCheckBox;
    private javax.swing.JButton processButton;
    private javax.swing.JTextField quantityField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField receiptNumberField;
    private javax.swing.JTextField remainingAmountField;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JButton searchItemButton;
    private javax.swing.JTable table;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JTextField totalDiscountField;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel tableModel;
//    private final DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

    private void onLoad() {
        initComponents();
        setVisible(true);
        AutoCompleteDecorator.decorate(itemComboBox);
        setComboBoxKeyAdapters(itemComboBox);
        datePicker.setFormats(yyyy_MM_dd);
//        KeyAdapter();
        tableModel = (DefaultTableModel) table.getModel();
        table.setDefaultRenderer(Object.class, coloredCellRenderer);
        clear();
    }

    private void setComboBoxKeyAdapters(JComboBox<? extends Object> comboBox) {
        String compName = comboBox.getName();
        Component component[] = comboBox.getComponents();
        for (Component component1 : component) {
            if (compName.equals("itemComboBox")) {
                component1.addKeyListener(itemComboBoxKeyAdapter);
            }
        }
    }
    KeyAdapter itemComboBoxKeyAdapter = new java.awt.event.KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent evt) {
            itemComboBoxKeyPressed(evt);
        }
    };

    private void clear() {
        tableModel.setRowCount(0);
        Combo.fillCustomers(customerComboBox);
        Combo.fillItems(itemComboBox);
        List<SaleInvoice> saleInvoices = manager.find(SaleInvoice.class);
        SaleInvoice[] saleInvoicesArray = new SaleInvoice[saleInvoices.size()];
        saleInvoices.toArray(saleInvoicesArray);
        Comparator<SaleInvoice> comparator = new Comparator<SaleInvoice>() {

            @Override
            public int compare(SaleInvoice o1, SaleInvoice o2) {
                Date o2Date = o2.getInvTime() == null ? new Date() : o2.getInvTime();
                return o2Date.compareTo(o1.getInvTime() == null ? new Date() : o1.getInvTime());
            }
        };
        Arrays.sort(saleInvoicesArray, comparator);
        historyComboBox.setModel(new DefaultComboBoxModel(saleInvoicesArray));
//        itemComboBoxWorker.execute();
        clearFields();
    }

    private void clearFields() {
        invoiceNumberField.setText("AUTO");//Data.getInvoiceNo()
        quantityField.setText("");
        priceField.setText("");
        quantityLabel.setText("");
        discountField.setText("");
        totalAmountField.setText("");
        totalDiscountField.setText("");
        paidAmountField.setText("");
        remainingAmountField.setText("");
        itemComboBox.requestFocus();
//        receiptNumberField.setText(Data.getReceiptNo());
    }
    double totalAmount = 0;

    private void calcTotal() {
        totalAmount = 0;
        double totalDiscount = 0;
        for (int i = 0; i < table.getRowCount(); i++) {
            totalAmount += Double.valueOf(table.getValueAt(i, 8).toString());
            totalDiscount += Double.valueOf(table.getValueAt(i, 6).toString());
        }
        totalAmountField.setText(nf2d.format(totalAmount));
        totalDiscountField.setText(nf2d.format(totalDiscount));
        String paidText = paidAmountField.getText();
        if (paidText.equals("")) {
            paidAmountField.setText("0");
            remainingAmountField.setText(nf2d.format(totalAmount));
        }
        calcRemaining();
        rowNumbers();
    }

    private void calcRemaining() {
        String totalAmountText = totalAmountField.getText().trim();
        totalAmountText = totalAmountText.equals("") ? "0" : totalAmountText;
        String paidAmountText = paidAmountField.getText().trim();
        paidAmountText = paidAmountText.equals("") ? "0" : paidAmountText;
        double totalAmount1 = 0, paidAmount = 0, remainingAmount;
        try {
            totalAmount1 = Double.parseDouble(totalAmountText);
        } catch (NumberFormatException e) {
        }
        if (totalAmount1 == 0) {
            return;
        }
        try {
            paidAmount = Double.parseDouble(paidAmountText);
        } catch (NumberFormatException e) {
        }
        remainingAmount = totalAmount1 - paidAmount;
        remainingAmountField.setText(nf2d.format(remainingAmount));
    }

    private void addToTable() {
        double quantity = 0;
        double price = 0;
        double discount = 0;
        double net;
        Item item = (Item) itemComboBox.getSelectedItem();
        if (item == null) {
            return;
        }
        String code = item.getCode();
        String description = item.getDescription();
        for (int i = 0; i < table.getRowCount(); i++) {

            if (description.equalsIgnoreCase("OTHER")) {
                break;
            }
            if (code.equals(table.getValueAt(i, 1))) {
                tableModel.removeRow(i);
                break;

            }
        }
        item = manager.find(Item.class, item.getCode());
        double availableQuantity = 0.0;

        try {
            availableQuantity = FindMySql.quantityByItemCode(item.getCode());
            quantity = Double.valueOf(quantityField.getText());
            price = Double.valueOf(priceField.getText().trim());
            discount = Double.valueOf(discountField.getText().trim());
        } catch (NumberFormatException e) {
        }

        if (quantity
                == 0) {
            showError("Quantity Required");
            return;
        }

        if (quantity > availableQuantity) {
            showError("Out of stock!");

//            int option = JOptionPane.showConfirmDialog(null, "Change Stock?", "Quantity Not Enough", JOptionPane.OK_CANCEL_OPTION);
//            if (option == JOptionPane.OK_OPTION) {
//                String newQuantityString = JOptionPane.showInputDialog("Stock for " + item.getCode() + " " + item.getDescription());
//                try {
//                    double newQuantity = Double.parseDouble(newQuantityString);
//                    Stock stock = manager.find(Stock.class, item.getCode());
//                    stock.setQuantity(newQuantity);
//                    manager.update(stock);
//                } catch (NumberFormatException numberFormatException) {
//                }
//            }
//
//            return;
        }

//        if (price == 0) {
//            setStatusMessage("Price Required", Color.RED);
//            showError("Price Required");
//            return;
//        }
        net = price * quantity;
        double discountAmount = net * discount / 100;
        double amount = net - discountAmount;
//        int i = dtm.getRowCount();
        Object[] rowData = {"",
            code,
            item.getDescription(),
            nf2d.format(price),
            nf3d.format(quantity),
            nf2d.format(net),
            nf2d.format(discountAmount),
            nf2d.format(discount),
            nf2d.format(amount)};

        tableModel.addRow(rowData);

        quantityField.setText(
                "");
        priceField.setText(
                "");
        quantityLabel.setText(
                "");
        discountField.setText(
                "");
        itemComboBox.setSelectedItem(
                "");
        calcTotal();
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
//        Rectangle rectangle = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
//        setBounds(0, 50, rectangle.width, rectangle.height - 50);
        Combo.fillCustomers(customerComboBox);
        Combo.fillEmployees(employeeComboBox);
//        Combo.fillItems(itemComboBox);
//        customerComboBox.requestFocus();
        itemComboBox.requestFocus();
    }

    private void process() {
        int rowCount = table.getRowCount();
        if (rowCount == 0) {
            return;
        }

        String invoiceNumber = invoiceNumberField.getText();
        boolean edit = false;
        SaleInvoice saleInvoice = null;

        if (!invoiceNumber.equalsIgnoreCase("AUTO")) {
            saleInvoice = manager.find(SaleInvoice.class, invoiceNumber);
            if (saleInvoice
                    != null) {
                int option = JOptionPane.showConfirmDialog(null, "Sure to edit Invoice: " + invoiceNumber + " ?", "Edit " + invoiceNumber, JOptionPane.OK_CANCEL_OPTION);
                if (option == JOptionPane.OK_OPTION) {
                    edit = true;
                    removeOldItems((List<SaleInvoiceHasItem>) saleInvoice.getSaleInvoiceHasItemCollection());
                } else {
                    return;
                }
            }
        }
        invoiceNumber = edit ? invoiceNumber : Data.getInvoiceNo();
        String ReceiptNumber = Data.getReceiptNo();
        if (invoiceNumber.equals("")) {
            invoiceNumberField.requestFocus();
            return;
        }
        Date date = datePicker.getDate();
        if (date == null) {
            datePicker.requestFocus();
            return;
        } else if (yyyy_MM_dd.format(date).equals(yyyy_MM_dd.format(new Date()))) {
            date = new Date();
        }

        String totalAmountText = totalAmountField.getText().trim();
        String remainingAmountText = remainingAmountField.getText().trim();
        String totalDiscountText = totalDiscountField.getText().trim();
        totalDiscountText = totalDiscountText.equals("") ? "0" : totalDiscountText;
        double discount;
        try {
            discount = Double.parseDouble(totalDiscountText);
        } catch (NumberFormatException e) {
            showError("Invalid Amount");
            return;
        }

        String paidAmountText = paidAmountField.getText().trim();
        paidAmountText = paidAmountText.equals("") ? "0" : paidAmountText;

        double amount = Double.valueOf(totalAmountText);
        double credit = Double.valueOf(remainingAmountText);

        Customer customer = (Customer) customerComboBox.getSelectedItem();
        String customerName;
        if (paidAmountText.equalsIgnoreCase("FREE")) {
            paidAmountText = "0.0";
            amount = 0;
            customerName = "FREE";
        } else if (customer == null) {
            if (credit > 0) {
                showError("No Customer for credit");
                return;
            }
            customerName = JOptionPane.showInputDialog("Customer Name");
        } else if (customer.getCode().equals("000") || customer.getCode().equalsIgnoreCase("CASH")) {
            if (credit > 0) {
                showError("No Customer for credit");
                return;
            }
            customerName = JOptionPane.showInputDialog("Customer Name");
        } else {
            customerName = customer.getName();
        }
        double paidAmount;
        try {
            paidAmount = Double.parseDouble(paidAmountText);
        } catch (NumberFormatException e) {
            showError("Invalid Amount");
            paidAmountField.selectAll();
            return;
        }
        paidAmount = paidAmount > amount ? amount : paidAmount;
//        double discount = Double.valueOf(totalDiscountText);
        saleInvoice = saleInvoice == null ? new SaleInvoice(invoiceNumber) : saleInvoice;

        saleInvoice.setCustomer(customer);
        saleInvoice.setCustomerName(customerName);
        saleInvoice.setAmount(amount);
        saleInvoice.setCredit(credit);
        saleInvoice.setDiscount(discount);
        saleInvoice.setInvTime(edit ? saleInvoice.getInvTime() : date);
        saleInvoice.setReceivedAmount(0.0);
        saleInvoice.setInitialPayment(paidAmount);
        Object o = employeeComboBox.getSelectedItem();
        Employee employee = o instanceof Employee ? (Employee) o : Data.getOperator().getEmployee();
        saleInvoice.setOperator(Data.getOperator().getUsername());
        saleInvoice.setEmployee(employee);
        List<Serializable> serializables = new ArrayList<>();
        int temp = 0;

        for (int i = 0; i < rowCount; i++) {
            String code = table.getValueAt(i, 1).toString();
            double quantity = Double.valueOf(table.getValueAt(i, 4).toString());
            double rate = Double.valueOf(table.getValueAt(i, 3).toString());
            double itemDiscount = Double.valueOf(table.getValueAt(i, 6).toString());
            Item item;
            if (code.equalsIgnoreCase("00")) {
                String tempCode = "TEMP" + ++temp;
                item = new Item(tempCode);
                item.setDescription("OTHER");
                Stock stock = new Stock(tempCode);
                stock.setQuantity(quantity);
                item.setStock(stock);
//                serializables.add(stock);
                PriceList priceList = new PriceList(tempCode);
                priceList.setSellingPack(rate);
                priceList.setCostPack(0.0);
                item.setPriceList(priceList);
//                serializables.add(priceList);

            } else {
                item = manager.find(Item.class, code);
            }
            SaleInvoiceHasItemPK saleInvoiceHasItemPK = new SaleInvoiceHasItemPK(invoiceNumber, item.getCode());
            SaleInvoiceHasItem sihi = new SaleInvoiceHasItem(saleInvoiceHasItemPK);
//            if (edit) {
//                sihi = manager.find(SaleInvoiceHasItem.class, saleInvoiceHasItemPK);
//                if (sihi != null) {
//                    double oldQuantity = sihi.getQuantity();
//                    double oldCost = sihi.getCost();
//                    double oldDiscount = sihi.getDiscount();
//                    double oldRate = sihi.getRate();
//                    double deference = oldQuantity - quantity;
//
//                } else {
//                    sihi = new SaleInvoiceHasItem(saleInvoiceHasItemPK);
//                }
//            } else {
//                sihi = new SaleInvoiceHasItem(saleInvoiceHasItemPK);
//            }
            sihi.setSaleInvoice(saleInvoice);
            sihi.setQuantity(quantity);
            sihi.setDiscount(itemDiscount);
            if (item.getStock() == null) {
                return;
            }
            Stock stock = item.getStock();
            quantity = stock.getQuantity() - quantity;
            stock.setQuantity(quantity);
            sihi.setItem(item);
            PriceList priceList = item.getPriceList();
            sihi.setCost(priceList.getCostPack());
            sihi.setRate(rate);
            priceList.setSellingPack(rate);
            serializables.add(priceList);
            serializables.add(sihi);
            serializables.add(stock);
        }
        serializables.add(saleInvoice);
        if (paidAmount > 0) {
            if (ReceiptNumber.equals("")) {
                showError("Recipt Number Required!");
                return;
            }
            CollectionReceipt collectionReceipt = new CollectionReceipt(ReceiptNumber);
            collectionReceipt.setCollectedTime(date);
            collectionReceipt.setSaleInvoice(saleInvoice);
            collectionReceipt.setCash(paidAmount);
            collectionReceipt.setAmount(paidAmount);
            SaleCash saleCash = new SaleCash(ReceiptNumber);
            saleCash.setAmount(paidAmount);
            saleCash.setCollectionReceipt(collectionReceipt);
            collectionReceipt.setSaleCash(saleCash);
            saleInvoice.setReceivedAmount(paidAmount);
            serializables.add(saleCash);
            serializables.add(collectionReceipt);
        }

        if (manager.update(serializables)) {
//            SaleInvoicePaymentView.getInstance().fill(saleInvoice);
//            SaleInvoicePaymentView.display();
            if (printCheckBox.isSelected()) {
                try {
                    URL url = getClass().getResource("/com/nanos/nbiz/pos/jrxml/PosInvoice.jasper");
                    Object object = JRLoader.loadObject(url);//"src/com/nanosl/nbiz/gui/jrxml/report1.jasper"
                    if (object == null) {
                        showError("Unable to print");
                        return;
                    }
                    JasperReport report = (JasperReport) object;
                    Map<String, Object> params = Data.getParams();
                    params.put("invoice", invoiceNumber);
                    Printer.printPosInvoice(report, params);
                } catch (JRException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
            showSuccess("Invoice: " + invoiceNumber + " Update success");
            if (!edit) {
                Data.setInvoiceNo(invoiceNumber);
                Data.setReceiptNo(ReceiptNumber);
            }
            clear();
            lastInvoiceNumberField.setText("Last : " + invoiceNumber);
        } else {
            showError("Update failed");
        }
    }

    private void substractDiscount() {
        String totalDiscountText = totalDiscountField.getText().trim();
        double totalDiscount;
        try {
            totalDiscount = Double.parseDouble(totalDiscountText);
        } catch (NumberFormatException numberFormatException) {
            totalDiscount = 0;
        }
        totalAmountField.setText(nf2d.format(totalAmount - totalDiscount));
    }

    @Override
    public void componentOpened() {
        customerComboBox.requestFocus();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void searchCustomer() {
        SearchCustomerDialog searchCustomerDialog = new SearchCustomerDialog(null, true);
        Customer customer = searchCustomerDialog.customer;
        if (customer != null) {
            customerComboBox.setSelectedItem(customer);
            itemComboBox.requestFocus();
        } else {
            customerComboBox.requestFocus();
        }
    }

    private void searchItem() {
        SearchItemDialog searchItemDialog = new SearchItemDialog(null, true);
        Item item = searchItemDialog.item;
        if (item != null) {
            itemComboBox.setSelectedItem(item);
            quantityField.requestFocus();
        } else {
            itemComboBox.requestFocus();
        }
    }

    private void searchInvoice() {
        SearchInvoiceDialog searchInvoiceDialog = new SearchInvoiceDialog(null, true);
        SaleInvoice saleInvoice = searchInvoiceDialog.saleInvoice;
        if (saleInvoice != null) {
            fillInvoice(saleInvoice);
        } else {
            clear();
        }
    }

    private void rowNumbers() {
        for (int i = 0; i < table.getRowCount(); i++) {
            table.setValueAt(i + 1, i, 0);
        }
    }

    public void fillInvoice(String invoiceNumber) {
        SaleInvoice saleInvoice = manager.find(SaleInvoice.class, invoiceNumber);
        fillInvoice(saleInvoice);
    }

    public void fillInvoice(SaleInvoice saleInvoice) {
        if (saleInvoice != null) {
            invoiceNumberField.setText(saleInvoice.getInvNo());
            datePicker.setDate(saleInvoice.getInvTime());
            customerComboBox.setSelectedItem(saleInvoice.getCustomer());
            employeeComboBox.setSelectedItem(saleInvoice.getEmployee());
            totalAmountField.setText(nf2d.format(saleInvoice.getAmount()));
            totalDiscountField.setText(nf2d.format(saleInvoice.getDiscount()));
            paidAmountField.setText(nf2d.format(saleInvoice.getInitialPayment()));
            remainingAmountField.setText(nf2d.format(saleInvoice.getAmount() - saleInvoice.getReceivedAmount()));
            Collection<SaleInvoiceHasItem> saleInvoiceHasItems = saleInvoice.getSaleInvoiceHasItemCollection();
            tableModel.setRowCount(0);
            int r = 0;
            for (SaleInvoiceHasItem saleInvoiceHasItem : saleInvoiceHasItems) {
                double rate = saleInvoiceHasItem.getRate();
                double quantity = saleInvoiceHasItem.getQuantity();
                double net = rate * quantity;
                double discount = saleInvoiceHasItem.getDiscount();
                double amount = net - discount;

                Object[] row = {
                    nf3p.format(++r),
                    saleInvoiceHasItem.getItem().getCode(),
                    saleInvoiceHasItem.getItem().getDescription(),
                    nf2d.format(rate),
                    nf2d.format(quantity),
                    nf2d.format(net),
                    nf2d.format(discount),
                    nf2d.format(discount / amount * 100),
                    nf2d.format(amount)

                };
                tableModel.addRow(row);
            }
        }
    }

    private void removeOldItems(List<SaleInvoiceHasItem> saleInvoiceHasItemCollection) {
        List<Serializable> toEdit = new ArrayList<>();
        for (SaleInvoiceHasItem saleInvoiceHasItem : saleInvoiceHasItemCollection) {
            Stock stock = saleInvoiceHasItem.getItem().getStock();
            stock.setQuantity(stock.getQuantity() + saleInvoiceHasItem.getQuantity());
            toEdit.add(stock);
        }
        manager.update(toEdit);
        manager.delete(saleInvoiceHasItemCollection);
    }
}
